export const LOAD_DATA = 'LOAD_DATA';
export const START_LOADING = 'START_LOADING';
export const ON_CLICK_ANSWER = 'ON_CLICK_ANSWER';
export const ON_CLICK_NEXT_QUESTION = 'ON_CLICK_NEXT_QUESTION';
export const ON_CLICK_RESTART = 'ON_CLICK_RESTART';
export const ON_SET_PLAYING = 'ON_SET_PLAYING';
